services:
  tele:
    build: ./python/.
    container_name: tele
    restart: unless-stopped
    env_file: "python/token.env"
    volumes:
    - ./downloads:/app/downloads
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx_conf/nginx.conf:/etc/nginx/nginx.conf
      - ./downloads/videos:/usr/share/nginx/html/videos

  ffmpeg:
    build: ./ffmpeg/.
    container_name: ffmpeg
    volumes:
      - ./downloads/audio:/input
      - ./audio:/output
    restart: unless-stopped

  # icecast:
  #   image: tlan16/icecast
  #   container_name: icecast
  #   ports:
  #   - 8000:8000
  # ices:
  #   build: ./ices2/.
  #   container_name: ices2
  #   volumes:
  #     - ./ices2/ices_playlist.xml:/etc/ices2/
  #     - ./downloads/audio:/var/www/ices2/audio

