services:
  tele:
    build: ./python/.
    container_name: tele
    restart: unless-stopped
    env_file: "python/token.env"
    volumes:
    - ./downloads:/app/downloads
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx_conf/nginx.conf:/etc/nginx/nginx.conf
      - ./downloads:/usr/share/nginx/html/videos