services:
  tele:
    build: ./python/.
    container_name: tele
    restart: unless-stopped
    env_file: "python/token.env"
    volumes:
    - ./downloads:/app/downloads
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx_conf/nginx.conf:/etc/nginx/nginx.conf
      - ./downloads:/usr/share/nginx/html/videos
  ice:
    image: moul/icecast
    container_name: ice
    volumes:
    - ./logs:/var/log/icecast2
    - /etc/localtime:/etc/localtime:ro
    environment:
    - ICECAST_SOURCE_PASSWORD=aaa
    - ICECAST_ADMIN_PASSWORD=bbb
    - ICECAST_PASSWORD=ccc
    - ICECAST_RELAY_PASSWORD=ddd
    ports:
    - 8000:8000
