services:
  tele:
    build: ./python/.
    container_name: tele
    restart: unless-stopped
    env_file: "python/token.env"
    volumes:
    - ./downloads:/app/downloads
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx_conf/nginx.conf:/etc/nginx/nginx.conf
      - ./downloads/videos:/usr/share/nginx/html/videos

  ffmpeg:
    build: ./ffmpeg/.
    container_name: ffmpeg
    volumes:
      - ./downloads/audio:/input
      - ./audio:/output
    restart: unless-stopped

  icecast:
    image: tlan16/icecast
    container_name: icecast
    restart: always
    ports:
      - 8000:8000
    environment:
      - ICECAST_SOURCE_PASSWORD=sourcepass
      - ICECAST_ADMIN_PASSWORD=bbb
      - ICECAST_PASSWORD=ccc
      - ICECAST_RELAY_PASSWORD=ddd
      - ICECAST_HOSTNAME=localhost
    networks:
      - net

  ices2:
    depends_on:
      - icecast
    build: ./ices2/.
    container_name: ices2
    volumes:
      - ./ices2/ices-playlist.xml:/etc/ices2/ices-playlist.xml
      - ./audio:/etc/ices2/audio
    networks:
      - net

networks:
  net:
    driver: bridge

